import Header from '@/components/Header';
import '@/styles/globals.css';
import { QueryClient } from '@tanstack/react-query';
import { QueryClientProvider, Hydrate } from '@tanstack/react-query';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useState } from 'react';
import { Noto_Sans } from '@next/font/google';

const notoSans = Noto_Sans({ subsets: ['latin'], weight: '400' });

export const baseUrl = process.env.NEXT_PUBLIC_API_URL;

export default function App({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <Header />
          <Component {...pageProps} className={notoSans.className} />
        </Hydrate>
      </QueryClientProvider>
    </>
  );
}
